
---

- name: Change Ethernet Description and Assert
  hosts: nxos
  gather_facts: yes

  tasks:
  - nxos_facts:

  - debug: var=ansible_net_interfaces

  - nxos_interface:
      name: Ethernet1/1
      description: "uplink to core"

  - nxos_facts:

  - debug: var=ansible_net_interfaces['Ethernet1/1']['description']

  - name: assert for certain version
    assert:
       that:
       - "'{{ ansible_net_interfaces['Ethernet1/1']['description'] }}' is match('uplink to core')"

