---

- name: Lab 7 task
  hosts: nxos
  connection: httpapi
  gather_facts: yes

  tasks:
  - name: Change Interface Desc and MTU
    nxos_interface:
      name: "{{ interface }}"
      description: "{{ int_desc }}"
      mtu: "{{ int_mtu }}"
      admin_state: up

  - name: Retrieve updated configuration
    nxos_facts:

  - debug: var=ansible_net_interfaces['Ethernet1/2']

  - name: Assert MTU changs and description
    assert:
      that: 
      - "{{ ansible_net_interfaces['Ethernet1/2']['mtu'] }} == {{ int_mtu }}"
